const TECH_ICONS = [
  { label: "JavaScript",  logo: null, fallback: "JS"  },
  { label: "TypeScript",  logo: null, fallback: "TS"  },
  { label: "React",       logo: null, fallback: "⚛"   },
  { label: "Next.js",     logo: null, fallback: "N"   },
  { label: "Node.js",     logo: null, fallback: "⬡"   },
  { label: "Python",      logo: null, fallback: "Py"  },
  { label: "Go",          logo: null, fallback: "Go"  },
  { label: "Docker",      logo: null, fallback: "🐳"  },
  { label: "AWS",         logo: null, fallback: "AWS" },
  { label: "PostgreSQL",  logo: null, fallback: "🐘"  },
  { label: "Redis",       logo: null, fallback: "R"   },
  { label: "MongoDB",     logo: null, fallback: "M"   },
  { label: "GraphQL",     logo: null, fallback: "GQL" },
  { label: "Flutter",     logo: null, fallback: "Fl"  },
  { label: "Svelte",      logo: null, fallback: "S"   },
  { label: "Vue",         logo: null, fallback: "V"   },
  { label: "Kubernetes",  logo: null, fallback: "K8s" },
  { label: "Nginx",       logo: null, fallback: "Ng"  },
  { label: "Git",         logo: null, fallback: "⎇"   },
  { label: "Kafka",       logo: null, fallback: "Kfk" },
  { label: "Prisma",      logo: null, fallback: "P"   },
  { label: "Tailwind",    logo: null, fallback: "Tw"  },
  { label: "Expo",        logo: null, fallback: "Exp" },
  { label: "FastAPI",     logo: null, fallback: "FA"  },
  { label: "Vercel",      logo: null, fallback: "▲"   },
  { label: "GitHub",      logo: null, fallback: "GH"  },
  { label: "Figma",       logo: null, fallback: "◐"   },
  { label: "Kotlin",      logo: null, fallback: "Kt"  },
  { label: "MySQL",       logo: null, fallback: "SQL" },
  { label: "HTML5",       logo: null, fallback: "H5"  },
  { label: "CSS3",        logo: null, fallback: "CSS" },
  { label: "Jest",        logo: null, fallback: "J"   },
];
export default TECH_ICONS